version: 2

sphinx:
  builder: html
  configuration: docs/src/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: false
